
name: publish

on: [push]

jobs:
  publish-turtledb-com-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the turtledb-com Docker image
        run: |
          docker build . --tag ghcr.io/turtledb-com/turtledb-com:latest
          docker run ghcr.io/turtledb-com/turtledb-com:latest
          docker push ghcr.io/turtledb-com/turtledb-com:latest

