
name: publish

on: 
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: tell (SSH) DO droplet to run with new changes
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: turtledb.com
          username: root
          key: ${{ secrets.KEY }}
          script: |
            cd /srv/turtledb-com/
            git pull
            yarn
            yarn start
            pm2 restart turtledb-com
  # publish-turtledb-com-image:
  #   runs-on: ubuntu-latest
  #
  #   permissions:
  #     contents: read
  #     packages: write
  #
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #
  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #
  #     - name: Build the turtledb-com Docker image
  #       run: |
  #         docker build . --tag ghcr.io/turtledb-com/turtledb-com:latest
  #         docker push ghcr.io/turtledb-com/turtledb-com:latest
